In [3]:
import pandas as pd
import numpy as np

In [9]:
np.set_printoptions(precision = 1)
x1 = np.random.rand(2,5)*10

In [10]:
x2 = np.random.rand(2,5)* -10

In [11]:
np.concatenate([x1,x2])

array([[ 20.1,  49.4,  53.5, 100. ,  85.1],
       [ 58.1,  83.4,   8.8,   0.1,   3.2],
       [-97.8, -58.6, -25.2,  -0.8, -58.4],
       [-25.8, -10.4, -37.2, -11.2, -57.6]])

In [12]:
np.concatenate([x1,x2],axis=1)

array([[ 20.1,  49.4,  53.5, 100. ,  85.1, -97.8, -58.6, -25.2,  -0.8,
        -58.4],
       [ 58.1,  83.4,   8.8,   0.1,   3.2, -25.8, -10.4, -37.2, -11.2,
        -57.6]])

In [14]:
s1 = pd.Series(x1[0],index = ["a","b","c","d","e"])
s1

a    20.128510
b    49.356474
c    53.525414
d    99.970675
e    85.145872
dtype: float64

In [21]:
s2 = pd.Series(x2[0],index = ["c","d","e","f","g"])

## Para concatenar  series se utiliza el metodo concat

In [22]:
pd.concat([s1,s2],axis = 1)

0          1
a  20.128510        NaN
b  49.356474        NaN
c  53.525414 -97.778212
d  99.970675 -58.633366
e  85.145872 -25.154250
f        NaN  -0.832682
g        NaN -58.383867

## Para borrar el indice se utiliza reset_index

In [23]:
s1.reset_index(drop= True)

0    20.128510
1    49.356474
2    53.525414
3    99.970675
4    85.145872
dtype: float64

In [28]:
pd.concat([s1.reset_index(drop= True),s2.reset_index(drop= True)])

0    20.128510
1    49.356474
2    53.525414
3    99.970675
4    85.145872
0   -97.778212
1   -58.633366
2   -25.154250
3    -0.832682
4   -58.383867
dtype: float64

In [29]:
pd.concat([s1.reset_index(drop= True),s2.reset_index(drop= True)],axis = 1)

0          1
0  20.128510 -97.778212
1  49.356474 -58.633366
2  53.525414 -25.154250
3  99.970675  -0.832682
4  85.145872 -58.383867

In [30]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns = ["a","b"])

In [32]:
df2 = pd.DataFrame(np.random.rand(3,2)*-10,columns = ["a","b"])

## Para unir dos dataframes se utiliza concat

In [33]:
pd.concat([df1,df2])

a         b
0  2.984786  3.870989
1  4.216217  5.411019
2  8.472902  3.498952
0 -0.870076 -8.699182
1 -1.649456 -6.149721
2 -6.903922 -9.298318

In [34]:
pd.concat([df1,df2],axis = 1)

a         b         a         b
0  2.984786  3.870989 -0.870076 -8.699182
1  4.216217  5.411019 -1.649456 -6.149721
2  8.472902  3.498952 -6.903922 -9.298318

In [36]:
pd.concat([df1.reset_index(drop= True),df2.reset_index(drop= True)])

a         b
0  2.984786  3.870989
1  4.216217  5.411019
2  8.472902  3.498952
0 -0.870076 -8.699182
1 -1.649456 -6.149721
2 -6.903922 -9.298318

## append concatena dos dataframes

In [38]:
df1.append(df2)

a         b
0  2.984786  3.870989
1  4.216217  5.411019
2  8.472902  3.498952
0 -0.870076 -8.699182
1 -1.649456 -6.149721
2 -6.903922 -9.298318

## Transpone el dataframe

In [39]:
df1.T

0         1         2
a  2.984786  4.216217  8.472902
b  3.870989  5.411019  3.498952

In [40]:
np.array([10,8,5,0]) * np.array([0,1,6,12])

array([ 0,  8, 30,  0])

## Borrar columnas

In [42]:
df1.drop(columns=["a"])

b
0  3.870989
1  5.411019
2  3.498952

In [120]:
df_left = pd.DataFrame(
    {'X':['x0','x1','x2','x3'],
    'W':['w0','w1','w2','w3'],
    'Y':['y0','y1','y2','y3'],
    'Mix':['y2','y3','a2','a3']},
    index = ['y2','y3','a2','a3'])
df_left

X   W   Y Mix
y2  x0  w0  y0  y2
y3  x1  w1  y1  y3
a2  x2  w2  y2  a2
a3  x3  w3  y3  a3

In [119]:
df_right = pd.DataFrame(
    {'Z':['z2','z3','z4','z5'],
     'A':['a2','a3','a4','a5'],
     'Y':['y2','y3','y4','y5']},
    index = [2,3,4,5])
df_right

Z   A   Y
2  z2  a2  y2
3  z3  a3  y3
4  z4  a4  y4
5  z5  a5  y5

## para realizar la union de dos dataframes se utiliza merge. Se debe especificar el tipo de join en el parametro how, y con el parametro on se indica porrque columna se realiza el join

In [105]:
pd.merge(df_left,df_right,how="inner",on ="Y")

X   W   Y Mix   Z   A
0  x2  w2  y2  a2  z2  a2
1  x3  w3  y3  a3  z3  a3

In [111]:
pd.merge(df_left,df_right,how="left",on ="Y")

X   W   Y Mix    Z    A
0  x0  w0  y0  y2  NaN  NaN
1  x1  w1  y1  y3  NaN  NaN
2  x2  w2  y2  a2   z2   a2
3  x3  w3  y3  a3   z3   a3

In [112]:
pd.merge(df_left,df_right,how="right",on ="Y")

X    W   Y  Mix   Z   A
0   x2   w2  y2   a2  z2  a2
1   x3   w3  y3   a3  z3  a3
2  NaN  NaN  y4  NaN  z4  a4
3  NaN  NaN  y5  NaN  z5  a5

## La union se puede hacer por varias columnas

In [123]:
pd.merge(df_left,df_right,how="inner",on=['Y'])

X   W   Y Mix   Z   A
0  x2  w2  y2  a2  z2  a2
1  x3  w3  y3  a3  z3  a3

In [124]:
np.nan

nan

In [125]:
np.nan + 10

nan

In [127]:
np.nan > 0

False

In [128]:
pd.options.mode.use_inf_as_na = True

In [129]:
pd.NA + "Hola"

<NA>

## Para conocer si un objeto es nulo se utiliza isnull

In [130]:
df1.isnull()

a      b
0  False  False
1  False  False
2  False  False

## Saber el numero de variables nulas por columna

In [131]:
df1.isnull().sum()

a    0
b    0
dtype: int64

In [132]:
df1

a         b
0  2.984786  3.870989
1  4.216217  5.411019
2  8.472902  3.498952

## Para  llenar los valores nulos se utiliza fillna

In [134]:
df1.fillna(0)

a         b
0  2.984786  3.870989
1  4.216217  5.411019
2  8.472902  3.498952

In [135]:
df1.fillna(df1.median())

a         b
0  2.984786  3.870989
1  4.216217  5.411019
2  8.472902  3.498952

## Para agrupar se utiliza la funcion groupby

In [45]:
diamonds = pd.read_csv("diamonds.csv")


In [46]:
diamonds.groupby("cut").mean()

carat      depth      table        price         x         y  \
cut                                                                          
Fair       1.046078  64.045743  59.048850  4357.500932  6.250777  6.186495   
Good       0.848711  62.364545  58.693778  3926.403509  5.840275  5.852277   
Ideal      0.702759  61.709500  55.951754  3456.941201  5.507898  5.520224   
Premium    0.891409  61.265007  58.746328  4579.684543  5.973840  5.944843   
Very Good  0.806365  61.818152  57.956560  3981.664101  5.741171  5.770503   

                  z      volume   density  
cut                                        
Fair       3.985245  165.053067  0.001264  
Good       3.642477  136.368452  0.001240  
Ideal      3.401922  115.410977  0.001215  
Premium    3.650036  145.167917  0.001229  
Very Good  3.560096  131.010566  0.001228

## se realiza la agrupación y se especifica una columna

In [47]:
diamonds.groupby("cut")["carat"].mean()

cut
Fair         1.046078
Good         0.848711
Ideal        0.702759
Premium      0.891409
Very Good    0.806365
Name: carat, dtype: float64

## Para agrupar por varias columnas

In [48]:
diamonds.groupby(["cut","color"])["price"].mean()

cut        color
Fair       D        4291.061350
           E        3682.312500
           F        3827.003205
           G        4232.412141
           H        5135.683168
           I        4685.445714
           J        4975.655462
Good       D        3405.382175
           E        3423.644159
           F        3498.761852
           G        4105.907940
           H        4276.254986
           I        5078.532567
           J        4574.172638
Ideal      D        2629.094566
           E        2597.550090
           F        3374.526536
           G        3718.469070
           H        3889.334831
           I        4451.970377
           J        4918.186384
Premium    D        3623.767790
           E        3538.914420
           F        4325.099571
           G        4502.207806
           H        5198.354140
           I        5939.557814
           J        6294.591584
Very Good  D        3470.467284
           E        3214.652083
           F        377

## Para aplicar funciones al agrupamiento

In [49]:
diamonds.groupby(["cut","color"])["price"].aggregate(['min',np.mean,max])

min         mean    max
cut       color                         
Fair      D      536  4291.061350  16386
          E      337  3682.312500  15584
          F      496  3827.003205  17995
          G      369  4232.412141  18574
          H      659  5135.683168  18565
          I      735  4685.445714  18242
          J      416  4975.655462  18531
Good      D      361  3405.382175  18468
          E      327  3423.644159  18236
          F      357  3498.761852  18686
          G      394  4105.907940  18625
          H      368  4276.254986  18640
          I      351  5078.532567  18707
          J      335  4574.172638  18325
Ideal     D      367  2629.094566  18693
          E      326  2597.550090  18729
          F      408  3374.526536  18780
          G      361  3718.469070  18806
          H      357  3889.334831  18760
          I      348  4451.970377  18779
          J      340  4918.186384  18508
Premium   D      367  3623.767790  18575
          E      326  3538.914420  18477
          F      342  4325.099571  18791
          G      382  4502.207806  18741
          H      368  5198.354140  18795
          I      334  5939.557814  18823
          J      363  6294.591584  18710
Very Good D      357  3470.467284  18542
          E      352  3214.652083  18731
          F      357  3778.820240  18777
          G      354  3872.753806  18818
          H      337  4535.059243  18803
          I      336  5255.879568  18500
          J      336  5103.513274  18430

In [51]:
def mean_kilo(x):
    return np.mean(x)/1000

## Para agregar mas de una funcion al calculo se usa agregate

In [52]:
diamonds.groupby(["cut","color"])["price"].aggregate(['min',np.mean,max,mean_kilo]).head(5)

min         mean    max  mean_kilo
cut  color                                    
Fair D      536  4291.061350  16386   4.291061
     E      337  3682.312500  15584   3.682313
     F      496  3827.003205  17995   3.827003
     G      369  4232.412141  18574   4.232412
     H      659  5135.683168  18565   5.135683

## agg realiza la misma funcion que aggregate

In [58]:
diamonds.groupby(["cut","color"])["price"].agg(['min',np.mean,max,mean_kilo]).head(5)

min         mean    max  mean_kilo
cut  color                                    
Fair D      536  4291.061350  16386   4.291061
     E      337  3682.312500  15584   3.682313
     F      496  3827.003205  17995   3.827003
     G      369  4232.412141  18574   4.232412
     H      659  5135.683168  18565   5.135683

## Tambien se puede usar lambda para realizar el calculo de una funcion

In [57]:
diamonds.groupby(["cut","color"])["price"].apply(lambda x : x*2)

0         652
1         652
2         654
3         668
4         670
         ... 
53915    5514
53916    5514
53917    5514
53918    5514
53919    5514
Name: price, Length: 53920, dtype: int64

In [61]:
diccionario = {"tip":[min,max],"total_bill":[np.mean,np]}
diccionario

{'tip': [<function min>, <function max>],
 'total_bill': [<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>,
  <module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py'>]}

In [165]:
def filtro(x):
    return mean_kilo(x["price"]) > 4

In [169]:
diamonds.groupby("cut").filter(filtro)

carat      cut color clarity  depth  table  price     x     y     z  \
1       0.21  Premium     E      SI   59.8   61.0    326  3.89  3.84  2.31   
3       0.29  Premium     I      VS   62.4   58.0    334  4.20  4.23  2.63   
8       0.22     Fair     E      VS   65.1   61.0    337  3.87  3.78  2.49   
12      0.22  Premium     F      SI   60.4   61.0    342  3.88  3.84  2.33   
14      0.20  Premium     E      SI   60.2   62.0    345  3.79  3.75  2.27   
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...   
53908   0.79  Premium     E      SI   61.4   58.0   2756  6.03  5.96  3.68   
53910   0.71  Premium     E      SI   60.5   55.0   2756  5.79  5.74  3.49   
53911   0.71  Premium     F      SI   59.8   62.0   2756  5.74  5.73  3.43   
53914   0.72  Premium     D      SI   62.7   59.0   2757  5.69  5.73  3.58   
53918   0.86  Premium     H      SI   61.0   58.0   2757  6.15  6.12  3.74   

           volume   density      ColorGrade  
1       34.505856  0.001217       Colorless  
3       46.724580  0.001241  Near Colorless  
8       36.425214  0.001208       Colorless  
12      34.715136  0.001267       Colorless  
14      32.262375  0.001240       Colorless  
...           ...       ...             ...  
53908  132.254784  0.001195       Colorless  
53910  115.988754  0.001224       Colorless  
53911  112.813386  0.001259       Colorless  
53914  116.721246  0.001234       Colorless  
53918  140.766120  0.001222  Near Colorless  

[15389 rows x 13 columns]

## Encontrar datos duplicados

In [171]:
duplicados = pd.DataFrame({'a': ['w'] * 4 + ['x'] * 3 + ['y'] * 2 + ['z']+['v'], 
                   'b': [1, 1, 1, 1, 2, 2, 2, 3, 3, 4,5]})

In [172]:
duplicados.duplicated()

0     False
1      True
2      True
3      True
4     False
5      True
6      True
7     False
8      True
9     False
10    False
dtype: bool

In [173]:
duplicados.duplicated(keep="first")

0     False
1      True
2      True
3      True
4     False
5      True
6      True
7     False
8      True
9     False
10    False
dtype: bool

In [174]:
duplicados[~duplicados.duplicated()]

a  b
0   w  1
4   x  2
7   y  3
9   z  4
10  v  5

## Para borrar los registros duplicados

In [175]:
duplicados.drop_duplicates()

a  b
0   w  1
4   x  2
7   y  3
9   z  4
10  v  5

## Para eliminar los duplicados en una columna

In [179]:
duplicados.drop_duplicates(["a"], keep= 'last')

a  b
3   w  1
6   x  2
8   y  3
9   z  4
10  v  5

## Para definir bins se utiliza la funcion cut de pandas

In [82]:
pd.cut(diamonds["price"],bins = 3).value_counts()

(307.503, 6491.667]      43579
(6491.667, 12657.333]     7346
(12657.333, 18823.0]      2995
Name: price, dtype: int64

In [93]:
pd.cut(diamonds["price"],bins =[300000,600000,900000,1200000]).value_counts()

(900000, 1200000]    0
(600000, 900000]     0
(300000, 600000]     0
Name: price, dtype: int64